config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'divisions#index'
  resources :divisions do
    resources :employees
  end
  resources :projects do
    resources :employees
  end
  resources :employees
  resources :employee_projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :employees, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :division
  has_many :employee_projects
  has_many :projects, :through => :employee_projects
end

app/models/employee_project.rb
class EmployeeProject < ApplicationRecord
  belongs_to :employee
  belongs_to :project

  scope :available_projects, -> (employee_id) { where("employee.id != ?", "#{employee_id}")}
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :employee_projects
  has_many :employees, :through => :employee_projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController

  def index
    @divisions = Division.all
    render :index
  end

  def new
    @division = Division.new
    render :new
  end

  def create
    @division = Division.new(division_params)
    if @division.save
      flash[:notice] = "Division successfully added!"
      redirect_to divisions_path
    else
      render :new
    end
  end

  def edit
    @division = Division.find(params[:id])
    render :edit
  end

  def show
    @division = Division.find(params[:id])
    render :show
  end

  def update
    @division= Division.find(params[:id])
    if @division.update(division_params)
      redirect_to division_path(@division)
    else
      render :edit
    end
  end

  def destroy
    @division = Division.find(params[:id])
    @division.destroy
    redirect_to divisions_path
  end

  private
  def division_params
    params.require(:division).permit(:name)
  end

end

app/controllers/employee_projects_controller.rb
class EmployeeProjectsController < ApplicationController
  def new
    @employee = Employee.find(params[:id])
    @projects = Project.all - @employee.projects
    render :new
  end

  def create
    employee = Employee.find(params[:id])
    project = Project.find(params[:post][:project_id])
    employee.projects << project

    redirect_to employee_path(employee.id)
  end

  def destroy
    employee = Employee.find(params[:id])
    project = Project.find(params[:project_id])
    project.employees.delete(employee)
    redirect_to employee_path(employee)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = Employee.all
    render :index
  end

  def new
    @division = Division.find(params[:division_id])
    @employee = @division.employees.new
    render :new
  end

  def create
    @division = Division.find(params[:division_id])
    @employee = @division.employees.new(employee_params)
    # binding.pry
    if @employee.save
      flash[:notice] = "Employee successfully added!"
      redirect_to division_path(id: params[:division_id])
    else
      flash[:alert] = "Employee couldn't be added!"
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    render :edit
  end

  def show
    @employee = Employee.find(params[:id])
    render :show
  end

  def update
    @employee= Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to employee_path
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :division_id)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    render :index
  end

  def new
    @project = Project.new
    render :new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project successfully added!"
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    render :edit
  end

  def show
    @project = Project.find(params[:id])
    render :show
  end

  def update
    @project= Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/divisions/edit.html.erb
<% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
  <li><%= link_to @division.name, division_path(@division) %></li>
<% end %>

<h1>Edit Division</h1>

<% if @division.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% @division.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @division do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/divisions/index.html.erb
<h1>Divisions</h1>

<% if @divisions.any? %>
  <ul>
    <% @divisions.each do |division| %>
      <li><%= link_to division.name, division_path(division) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No divisions to show.</p>
<% end %>



<p><%= link_to "Add an division", new_division_path %></p>
<p><%= link_to "Projects", projects_path %></p>
<p><%= link_to "Employees", employees_path %></p>

app/views/divisions/new.html.erb
<% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
<% end %>

<h1>Add a new division:</h1>

<%= render "layouts/division_form" %>

app/views/divisions/show.html.erb
<% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
  <li><%= link_to @division.name, division_path(@division) %></li>
<% end %>

<div class="jumbotron">
  <h1><%= @division.name %></h1>
</div>

<% if @division.employees.any? %>
  <h4>Here are the employees for this division:</h4>
  <% @division.employees.each do |employee| %>
    <ul>
      <li>
        <%= link_to employee.name, division_employee_path(@division, employee) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No employees are listed for this division.</p>
<% end %>

<p><%= link_to "Add a employee", new_division_employee_path(@division) %></p>
<p><%= link_to "Edit", edit_division_path(@division) %></p>
<p><%= link_to "Delete division", division_path(@division),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<p><%= link_to "Return to divisions", divisions_path %></p>

app/views/employee_projects/new.html.erb
<h1>Assign <%= @employee.name %> to a New Project</h1>

<h4>Available Projects:</h4>
<% if @projects.any? %>
  <%= form_for @employee, :url => employee_projects_path(id: @employee.id), :method => "post" do |f| %>
    <%= collection_select(:post, :project_id, @projects, :id, :name) %>
    <%= f.submit "Add Employee to Project"%>
  <% end %>
<% else %>
  <p><%=@employee.name%> is already assigned to all projects. Maybe they deserve a raise!</p>
<% end %>

<p><%= link_to "Return to employee details", employee_path(@employee) %></p>
<p><%= link_to "All employees", employees_path %></p>

app/views/employees/edit.html.erb
<% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
  <li><%= link_to @employee.name, employee_path(@employee) %></li>
<% end %>

<h1>Edit Employee</h1>

<% if @employee.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @employee.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @employee do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<% if @employees.any? %>
  <ul>
    <% @employees.each do |employee| %>
      <li><%= link_to employee.name, employee_path(employee.id) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No employees to show.</p>
<% end %>

<p><%= link_to "Divisions", divisions_path %></p>
<p><%= link_to "Projects", projects_path %></p>

app/views/employees/new.html.erb
<% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
  <li><%= link_to @division.name, division_path(@division) %></li>
<% end %>

<div class="jumbotron">
  <h1><%= @division.name %></h1>
</div>

<h1>Add a new employee:</h1>

<%= render "layouts/errors", :object => @employee %>

<%= form_for @employee, :url => division_employees_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/employees/show.html.erb
<div class="jumbotron">
  <h1><%= @employee.name %></h1>
  <% if @employee.division_id %>
    <% division = Division.find(@employee.division_id)%>
    <h3>Division: <%= division.name %></h3>
  <% else %>
    <h2>Division: None</h2>
  <% end %>
</div>

<% if @employee.projects.any? %>
  <h3>Employee projects:</h3>
  <table>
    <% @employee.projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td class="remove-from-project"><%= link_to "Remove from project", employee_project_path(project_id: project.id),
                                :data => {:confirm => "Are you sure?",
                                               :method => "delete"} %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>No projects to show.</p>
<% end %>

<p><%= link_to "Add employee to a project", new_employee_project_path(id: @employee.id) %></p>
<p><%= link_to "Edit employee details", edit_employee_path(@employee) %></p>
<p><%= link_to "Delete employee", employee_path(@employee),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<p><%= link_to "Return to employees", employees_path %></p>

app/views/layouts/_division_form.html.erb
<%= render "layouts/errors", :object => @division %>

<%= form_for @division do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
<% end %>

<h1>Edit Project</h1>

<% if @project.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% @project.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @project do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% if @projects.any? %>
  <ul>
    <% @projects.each do |project| %>
      <li><%= link_to project.name, project_path(project) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No projects to show.</p>
<% end %>

<p><%= link_to "Add an project", new_project_path(@project) %></p>
<p><%= link_to "Divisions", divisions_path %></p>
<p><%= link_to "Employees", employees_path %></p>

app/views/projects/new.html.erb
<% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
  <li><%= link_to "Projects", projects_path %></li>
<% end %>

<h1>Add a new project:</h1>

<% if @project.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% @project.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @project do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<div class="jumbotron">
  <h1><%= @project.name %></h1>
</div>

<% if @project.employees.any? %>
  <h4>Here are the employees for this project:</h4>
  <% @project.employees.each do |employee| %>
    <ul>
      <li>
        <%= link_to employee.name, project_employee_path(@project, employee) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No employees are listed for this project.</p>
<% end %>

<p><%= link_to "Edit", edit_project_path(@project) %></p>
<p><%= link_to "Delete project", project_path(@project),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<p><%= link_to "Return to projects", projects_path %></p>